// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://hwdpepjgletwoljonqnt.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3ZHBlcGpnbGV0d29sam9ucW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0MDQwNDEsImV4cCI6MjA0Nzk4MDA0MX0.lU6w_dmNyb42d2nclyWRiu20l1FvFPkPz2ffvPQeCCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);